api_platform:

  title: 'Test API'

  mapping:
    paths: ['%kernel.project_dir%/src/Entity']

  eager_loading:
    max_joins: 100

  formats:
    json: [ 'application/json' ]
    jsonld: [ 'application/ld+json' ]
    jsonhal: [ 'application/hal+json' ]
    jsonapi: [ 'application/vnd.api+json' ]
    xml: [ 'application/xml', 'text/xml' ]
    yaml: [ 'application/x-yaml' ]
    csv: [ 'text/csv' ]
    html: [ 'text/html' ]
  patch_formats:
    json: [ 'application/merge-patch+json' ]
    jsonapi: [ 'application/vnd.api+json' ]
  swagger:
    api_keys:
      apiKey:
        name: Authorization
        type: header
  # Good cache defaults for REST APIs
  defaults:
    formats: ['json', 'jsonld']
    stateless: true
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]
    extra_properties:
      standard_put: true
